apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.name }}"
spec:
  storageClassName: minikube-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi