
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.name }}"
  labels:
    type: local
spec:
  #we use local node storage here!
  #kubectl get storageclass
  storageClassName: minikube-hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.persistentVolume.hostPath }}" 